### ISSUE TITLE
spotifywm not working

### ISSUE THREAD

**Issue by patrickaldis** [the-argus/spicetify-nix#10]
I'm using `pkgs.spotifywm` rather than `pkgs.spotify`, which sets the window title class to "Spotify" before loading the spotify window. I was hoping it would be as easy as setting `spotifyPackage = pkgs.spotifywm;` but this doesn't seem to do the trick - the client launches but without any themeing.

Thanks for any help, my hm config is here:

```
{pkgs, spicetify-nix, ...}:
{
  imports = [
    spicetify-nix.homeManagerModule
  ];
  programs.spicetify = {
    enable = true;
    spotifyPackage = pkgs.spotifywm; 
    theme = "catppuccin-mocha";
    colorScheme = "flamingo";

    enabledExtensions = [
      "fullAppDisplay.js"
      "songStats.js"
      "keyboardShortcut.js"
      "fullAlbumDate.js"
      "wikify.js"
      "history.js"
      "genre.js"
    ];
  };
}
```

**Comment by the-argus** [comment]
@patrickaldis Finally got around to this. setting ``spotifyPackage = pkgs.spotifywm`` should work now.

**Comment by spikespaz** [comment]
@the-argus Probably don't encourage the way that the `spotifywm` package does this in Nixpkgs. That package I don't think is well behaved. Since it is a patch, it should behave as one, and use the same binary name as the package that it "overrides". I recommend saying such, that it is unsupported and instead integrating an option to wrap the provided package with the requisite `LD_PRELOAD` variable.

**Comment by the-argus** [comment]
@spikespaz take a look at 4fcacee and let me know what you think. Also, why not just make a nixpkgs PR?

**Comment by spikespaz** [comment]
> @spikespaz take a look at [4fcacee](https://github.com/the-argus/spicetify-nix/commit/4fcacee929b6ab3242df2652c7ee00bf4798f0cb) and let me know what you think. Also, why not just make a nixpkgs PR?

Left some comments, LGTM.
PR: No reason not to, but the maintainer might have a different opinion. I just decided it wasn't worth breaking peoples setups when it's such a low priority change. I'd imagine there's a few people out there who just wrapped it themselves. Anyway, jqueiroz made the first commit <https://github.com/NixOS/nixpkgs/commit/2b1d4611d19755cfe62d3a0ee6476deccf10e1bd> and hasn't touched it since.

**Comment by the-argus** [comment]
I'm going to go ahead and make a PR, ill keep ``bin/spotifywm`` as a symlink to ``bin/spotify``. Also going to merge my fixing commit.

**Comment by the-argus** [comment]
@spikespaz I would appreciate a review: https://github.com/NixOS/nixpkgs/pull/222348

**Comment by the-argus** [comment]
the PR i made to nixpkgs got merged- closing this because with newer versions of nixpkgs, namely unstable, spotifywm should just work with spicetify nix as OP originally tried.
