### ISSUE TITLE
Dribblish rendering issue

### ISSUE THREAD

**Issue by elythh** [the-argus/spicetify-nix#29]
Hello, this is how Dribblish render with the latest Spotify.
![28-07-2023-09:54:11](https://github.com/the-argus/spicetify-nix/assets/50964650/161c1bd5-7475-447b-91b7-e106b7d03690)
Does anyone know which CSS I can use to fix it ? Thank you !

**Comment by elythh** [comment]
Using the latest release from `spicetify-themes`
![image](https://github.com/the-argus/spicetify-nix/assets/50964650/6c4dc9a6-70f6-45d0-a82d-06e31a75e594)

```nix
{ colors, spicetify-nix, pkgs }:
let
  spicePkgs = spicetify-nix.packages.${pkgs.system}.default;
in

{
  imports = [ spicetify-nix.homeManagerModule ];
  programs.spicetify =
    let
      # use a different version of spicetify-themes than the one provided by
      # spicetify-nix
      officialThemesOLD = pkgs.fetchgit {
        url = "https://github.com/spicetify/spicetify-themes";
        rev = "b2269a9650b735b955d5b024d69c7a38022d4a7e";
        sha256 = "pWMswQJ7uGBPTmlZjdHoBXdVAOr3VKv+PbKZt0+G2Qg=";
      };
    in
    {
      enable = true;
      enabledExtensions = with spicePkgs.extensions; [
        playlistIcons
        # spicetify-nix.packages.${pkgs.system}.default.extensions.adblock
        genre
        historyShortcut
        # hidePodcasts
        # fullAppDisplay
        shuffle
      ];
      colorScheme = "custom";
      theme = {
        name = "Dribbblish";
        src = officialThemesOLD;
        requiredExtensions = [
          # define extensions that will be installed with this theme
          {
            # extension is "${src}/Dribbblish/dribbblish.js"
            filename = "dribbblish.js";
            src = "${officialThemesOLD}/Dribbblish";
          }
        ];
        # changes to make to config-xpui.ini for this theme:
        patches = {
          "xpui.js_find_8008" = ",(\\w+=)32,";
          "xpui.js_repl_8008" = ",$\{1}56,";
        };
        appendName = true; # theme is located at "${src}/Dribbblish" not just "${src}"
        injectCss = true;
        replaceColors = true;
        overwriteAssets = true;
        sidebarConfig = true;
      };
      # color definition for custom color scheme. (rosepine)
      customColorScheme = with colors;
        {
          text = "${color7}";
          subtext = "${color15}";
          sidebar-text = "${color7}";
          main = "${background}";
          sidebar = "${mbg}";
          player = "${bg2}";
          card = "${color0}";
          shadow = "${color8}";
          selected-row = "${color8}";
          button = "${color4}";
          button-active = "${color4}";
          button-disabled = "${color5}";
          tab-active = "${color4}";
          notification = "${color3}";
          notification-error = "${color1}";
          misc = "${comment}";
        };
    };
}
```

**Comment by the-argus** [comment]
@elythh I updated all the inputs and Dribbblish is fixed. The latter screenshot you sent can also be seen in this (resolved) spicetify themes issue: https://github.com/spicetify/spicetify-themes/issues/969
There were many other issues:
https://github.com/spicetify/spicetify-themes/issues/950
https://github.com/spicetify/spicetify-themes/issues/934
https://github.com/spicetify/spicetify-themes/issues/931

I also have known about this for a while (and switched from Dribbblish to OnePunch) and I commented on one of these issues: https://github.com/spicetify/spicetify-themes/issues/892

Anyways yeah uh. The spicetify-themes maintainer seems quite overwhelmed with requests to fix dribbblish. And I don't think they're going to be fixed in spicetify-nix. So for future reference please check what happens in a non-nix install before making an issue here regarding rendering problems

It's worth mentioning also that Dribbblish looks a bit different now with the new spotify style, and we still do have a known issue: #33

**Comment by elythh** [comment]
My mistake, I thought it was nix related indeed. Thank you for your answer and for taking the time to provide the necessary links.
