### ISSUE TITLE
Custom plugins?

### ISSUE THREAD

**Issue by Jan64X** [the-argus/spicetify-nix#58]
I'd love to use the "Beautiful Lyrics" plugin, [Link](https://github.com/surfbryce/beautiful-lyrics), but there doesn't seem to be a directory for custom .js files. Any way to do so and if not, can we add the plugin to this app?
Thanks in advance!

**Comment by xhos** [comment]
I spent a few hours figuring out how this flake works because I also wanted to use Beautiful Lyrics on NixOS. I conclude that it is currently impossible as far as I understand. It's not hard to add a new plugin, it's just a matter of finding the plugins .js file, but Beautiful Lyrics specifically doesn't have one as of recently, due to author rewriting it and using some other way, idk. Even if it is possible it requires major changes in this repo, and as far as I can see it's pretty abandoned here.. 

Maybe I'll be able to find an old .js file and somehow configure it to work, if I do I'll let you know

**Comment by Brisingr05** [comment]
I would suggest using [this fork](https://github.com/Gerg-L/spicetify-nix) of spiectify-nix. It's actively maintained and includes 'Beautiful Lyrics'. There's a [page](https://wiki.nixos.org/wiki/Spicetify-Nix) for it in the official wiki as well.
